baseURL = 'https://blog.flysan.xyz'
languageCode = 'en-us'
title = 'fly'
theme = 'ananke'

DefaultContentLanguage = "en"
googleAnalytics = ""
enableRobotsTXT = true
sectionPagesMenu = "main"
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[pagination]
  pagerSize = 15

[params]
  text_color = ""
  author = "fly"
  favicon = ""
  site_logo = "static/images/cit-tum-favicon.png"
  description = "bababooey"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[menu]
[[menu.blog]]
  pre = "<i class='fa fa-heart'></i>"
  weight = -110
  identifier = 'blog'
  name = 'Blog'
  url = '/blog/'


[[params.ananke_socials]]
name = "github"
url = "https://github.com/fly-san"
